language: julia

os:
  - linux

julia:
  - 1.3

branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'if Sys.islinux() && string(VERSION)[1:3] == "1.3"
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    end'
